/* brands.js — hand-maintained brand-study palettes. UNLIKE colors.js (generated by
   scripts/extract.py, never hand-edited), this file is authored by hand and survives book
   regenerations.
   Rules: section is always "Brands" (one chip in the app; the strategy grouping below is
   file organization only); page is a synthetic unique id ≥ 900 (the book ends far below) and once assigned
   NEVER changes — saved builds and share links key on it; colors are UPPERCASE #RRGGBB.
   Confidence convention, checked against the brands' OWN sites (2026-08):
     ✅ = the company itself currently publishes these hex values
     ≈  = reference values — the colour (or its name) is official, but the company does not
          publish a hex; sampled/commonly-cited, verify against official assets before
          production use.
   These are brand-STUDY palettes: the most recognizable references, not complete production
   systems. The file is organized by visual strategy — how each brand "owns" its colour. */
const BRANDS = [

  /* ---- Minimal / premium: black, white, neutrals ---- */
  /* ≈ Apple — black/white identity; grays sampled from apple.com's digital ground */
  { name: "Apple", section: "Brands", page: 919, colors: ["#000000", "#F5F5F7", "#86868B", "#FFFFFF"] },
  /* ≈ Nike — black and white, full stop */
  { name: "Nike", section: "Brands", page: 920, colors: ["#111111", "#FFFFFF"] },
  /* ≈ Notion — black/white + warm off-white ground */
  { name: "Notion", section: "Brands", page: 921, colors: ["#000000", "#F7F6F3", "#FFFFFF"] },
  /* ≈ Patagonia — black/white identity; nature & product photography carries the colour */
  { name: "Patagonia", section: "Brands", page: 917, colors: ["#000000", "#FFFFFF"] },

  /* ---- Bold single-colour: one memorable hero colour + neutrals ---- */
  /* ✅ brand.netflix.com — Netflix Red + Symbol Dark Red, published hexes */
  { name: "Netflix", section: "Brands", page: 907, colors: ["#E50914", "#B20710", "#000000", "#FFFFFF"] },
  /* ✅ discord.com/branding — Blurple, Light Blurple, Black, published hexes */
  { name: "Discord", section: "Brands", page: 926, colors: ["#5865F2", "#E0E3FF", "#000000", "#FFFFFF"] },
  /* ✅ redditinc.com brand guidelines — OrangeRed, Urchin, Gold, Mango, published hexes */
  { name: "Reddit", section: "Brands", page: 927, colors: ["#FF4500", "#172E35", "#FFD635", "#FFA800"] },
  /* ✅ brand.klarna.com/brand-colors — Klarna Pink, Klarna Black, Off White */
  { name: "Klarna", section: "Brands", page: 901, colors: ["#FFA8CD", "#0B051D", "#F9F8F5"] },
  /* ✅ Atlassian — Pacific Bridge, Squid Ink, Fine Pine; published, but that guideline is now
     DEPRECATED in favour of their token-based system — don't copy blindly into production */
  { name: "Atlassian", section: "Brands", page: 936, colors: ["#0052CC", "#172B4D", "#36B37E", "#FFFFFF"] },
  /* ≈ Spotify — current brand green on black/white */
  { name: "Spotify", section: "Brands", page: 905, colors: ["#1ED760", "#000000", "#FFFFFF"] },
  /* ≈ Airbnb — the coral is officially named "Rausch" but no hex is published */
  { name: "Airbnb", section: "Brands", page: 911, colors: ["#FF385C", "#222222", "#FFFFFF"] },
  /* ≈ Pinterest — official red circle, hex not exposed in the current guideline */
  { name: "Pinterest", section: "Brands", page: 923, colors: ["#E60023", "#111111", "#FFFFFF"] },
  /* ≈ Tiffany & Co. — Tiffany Blue (their trademarked colour) on black/white */
  { name: "Tiffany & Co.", section: "Brands", page: 932, colors: ["#81D8D0", "#000000", "#FFFFFF"] },
  /* ≈ Bolt — Jungle Green from the bolt.eu refresh */
  { name: "Bolt", section: "Brands", page: 902, colors: ["#32BB78", "#000000", "#FFFFFF"] },
  /* ≈ Stripe — Blurple, Slate, Cyan, Black Squeeze as used on stripe.com */
  { name: "Stripe", section: "Brands", page: 904, colors: ["#635BFF", "#0A2540", "#00D4FF", "#F6F9FC"] },
  /* ≈ Framer — Framer blue on black */
  { name: "Framer", section: "Brands", page: 912, colors: ["#0055FF", "#000000", "#FFFFFF"] },
  /* ≈ Telia — Telia Purple + deep purple */
  { name: "Telia", section: "Brands", page: 913, colors: ["#990AE3", "#29003E", "#FFFFFF"] },
  /* ≈ YouTube — red + almost-black */
  { name: "YouTube", section: "Brands", page: 922, colors: ["#FF0000", "#0F0F0F", "#FFFFFF"] },
  /* ≈ LinkedIn — blue + black */
  { name: "LinkedIn", section: "Brands", page: 924, colors: ["#0A66C2", "#000000", "#FFFFFF"] },
  /* ≈ Twitch — purple + near-black */
  { name: "Twitch", section: "Brands", page: 925, colors: ["#9146FF", "#0E0E10", "#FFFFFF"] },
  /* ≈ GitHub — dark + blue accent */
  { name: "GitHub", section: "Brands", page: 928, colors: ["#24292F", "#0969DA", "#FFFFFF"] },

  /* ---- Playful multicolour: several saturated colours working as a system ---- */
  /* ✅ design.duolingo.com/identity/color — the full published Feather palette: Feather Green,
     Mask Green, Macaw, Cardinal, Bee, Fox, Beetle, Eel, Snow. The strongest documented
     palette in this file — a complete core/secondary/neutral hierarchy, not just logo colours */
  { name: "Duolingo", section: "Brands", page: 914, colors: ["#58CC02", "#89E219", "#1CB0F6", "#FF4B4B", "#FFC800", "#FF9600", "#CE82FF", "#4B4B4B", "#FFFFFF"] },
  /* ✅ brand.mastercard.com — the interlocking-circles trio, published hexes */
  { name: "Mastercard", section: "Brands", page: 935, colors: ["#EB001B", "#FF5F00", "#F79E1B"] },
  /* ≈ Figma — logo mark colours; official assets exist but no published hex table */
  { name: "Figma", section: "Brands", page: 909, colors: ["#F24E1E", "#FF7262", "#A259FF", "#1ABCFE", "#0ACF83"] },
  /* ≈ Google — the G's colours; Google's guideline says don't recolor the asset rather than
     publishing a corporate hex palette */
  { name: "Google", section: "Brands", page: 910, colors: ["#4285F4", "#EA4335", "#FBBC05", "#34A853"] },
  /* ≈ LEGO — official RGB/SVG logo assets exist, but no published hex table; sample the
     official asset for production work */
  { name: "LEGO", section: "Brands", page: 918, colors: ["#D01012", "#FFCF00", "#000000", "#FFFFFF"] },
  /* ≈ Slack — primary purple + the four logo colours */
  { name: "Slack", section: "Brands", page: 908, colors: ["#611F69", "#36C5F0", "#2EB67D", "#ECB22E", "#E01E5A"] },

  /* ---- High-contrast mass-market: two highly recognizable contrasting colours ---- */
  /* ≈ IKEA — blue/yellow is the confirmed key combination ("the blue creates attention, the
     yellow conveys optimism") but IKEA publishes no hex; digital references only */
  { name: "IKEA", section: "Brands", page: 906, colors: ["#0058A3", "#FFDA1A", "#FFFFFF"] },
  /* ≈ McDonald's — golden-arches yellow + red */
  { name: "McDonald's", section: "Brands", page: 929, colors: ["#FFC72C", "#DA291C", "#FFFFFF"] },
  /* ≈ Coca-Cola — commonly cited Coca-Cola Red */
  { name: "Coca-Cola", section: "Brands", page: 930, colors: ["#F40009", "#000000", "#FFFFFF"] },
  /* ≈ FedEx — purple + orange */
  { name: "FedEx", section: "Brands", page: 934, colors: ["#4D148C", "#FF6600", "#FFFFFF"] },
  /* ≈ ICA — sampled from ica.se's own markup: classic logo red + current digital red */
  { name: "ICA", section: "Brands", page: 903, colors: ["#E3000B", "#EB1F07", "#FFFFFF"] },
  /* ≈ Starbucks — green + dark green on cream */
  { name: "Starbucks", section: "Brands", page: 931, colors: ["#00754A", "#1E3932", "#F2F0EB", "#FFFFFF"] },
  /* ≈ Barbie — commonly cited Barbie Pink + light pink */
  { name: "Barbie", section: "Brands", page: 933, colors: ["#E0218A", "#F7B9D7", "#FFFFFF"] },

  /* ---- Editorial / expressive: photography, type and art direction carry as much as the logo colours ---- */
  /* ≈ Mailchimp — "Cavendish Yellow" and "Peppercorn" are the official NAMES, but the current
     public page exposes no hex; these are reference values */
  { name: "Mailchimp", section: "Brands", page: 915, colors: ["#FFE01B", "#241C15"] },
  /* ≈ Dropbox — brand.dropbox.com describes a deliberately diverse system of Core Colors,
     Accent Colors and Greys with no simple hex list; this is only the recognizable anchor
     blue + digital ground, NOT the identity reduced to three values */
  { name: "Dropbox", section: "Brands", page: 916, colors: ["#0061FF", "#1E1919", "#F7F5F2"] },
];
